services:
  geth:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-testnets'
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.my-holesky-rpc-router.tls=true'
        - 'traefik.http.routers.my-holesky-rpc-router.rule=Host(`holesky.dark.florist`)'
        - 'traefik.http.routers.my-holesky-rpc-router.service=my-holesky-rpc-service'
        - 'traefik.http.services.my-holesky-rpc-service.loadbalancer.server.port=8545'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # https://hub.docker.com/layers/ethpandaops/geth/multicall/images/sha256-6bbb13aac646392c7650341aa95c00345f12fbabd80bd304d5ff4aaed6dec043?context=explore amd64
    image: 'ethpandaops/geth:multicall@sha256:0918974bf76ebaa84b87ad7d340e909e31a39aba894be142e9db91d62e910c91'
    command:
      - '--holesky'
      - '--datadir=/data'
      - '--http'
      - '--http.addr=0.0.0.0'
      - '--http.port=8545'
      - '--http.vhosts=*'
      - '--http.corsdomain=*'
      - '--http.rpcprefix=/' # serve on all paths
      - '--cache=2048'
      - '--maxpeers=40'
      - '--authrpc.addr=0.0.0.0'
      - '--authrpc.port=8551'
      - '--authrpc.vhosts=*'
      - '--authrpc.jwtsecret=/run/secrets/jwt.hex'
      - '--state.scheme=path'
      - '--port=30304'
      - '--discovery.port=30304'
    networks:
      traefik:
      internal:
        aliases:
          - 'geth-internal'
      public-facing:
    ports:
      - target: 30304
        published: 30304
        protocol: 'tcp'
        mode: 'host'
      - target: 30304
        published: 30304
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'geth-data'
        target: '/data'

  lodestar:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-testnets'
    image: 'chainsafe/lodestar:v1.17.0@sha256:54b2400f49f1db0efbf76bf74173d1fdea2c081090eb15ae0094a87118704066'
    command:
      - 'beacon'
      - '--dataDir=/data'
      - '--rest'
      - '--rest.address=0.0.0.0'
      - '--rest.namespace=*'
      - '--execution.urls=http://geth-internal:8551'
      - '--network=holesky'
      - '--port=9001'
      - '--metrics'
      - '--checkpointSyncUrl=https://beaconstate-holesky.chainsafe.io'
      - '--jwt-secret=/run/secrets/jwt.hex'
    environment:
      NODE_OPTIONS: '--max-old-space-size=8192'
    networks:
      internal:
      public-facing:
    ports:
      - target: 9001
        published: 9001
        protocol: 'tcp'
        mode: 'host'
      - target: 9001
        published: 9001
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'lodestar-data'
        target: '/data'

secrets:
  jwt-secret.hex:
    external: true

networks:
  internal:
  public-facing:
    external: true
  traefik:
    external: true

volumes:
  geth-data:
  lodestar-data:
