services:
  geth:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-testnets'
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.my-holesky-rpc-router.tls=true'
        - 'traefik.http.routers.my-holesky-rpc-router.rule=Host(`holesky.dark.florist`)'
        - 'traefik.http.routers.my-holesky-rpc-router.service=my-holesky-rpc-service'
        - 'traefik.http.services.my-holesky-rpc-service.loadbalancer.server.port=8545'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # https://hub.docker.com/layers/ethereum/client-go/release-1.15/images/sha256-fb9553bdae51e82d55e574b4935d0101b640097174ad93457ea7d81abb6b5e68 amd64
    image: 'ethereum/client-go:v1.15.5@sha256:fb9553bdae51e82d55e574b4935d0101b640097174ad93457ea7d81abb6b5e68'
    command:
      - '--holesky'
      - '--datadir=/data'
      - '--http'
      - '--http.addr=0.0.0.0'
      - '--http.port=8545'
      - '--http.vhosts=*'
      - '--http.corsdomain=*'
      - '--http.rpcprefix=/' # serve on all paths
      - '--cache=2048'
      - '--maxpeers=40'
      - '--authrpc.addr=0.0.0.0'
      - '--authrpc.port=8551'
      - '--authrpc.vhosts=*'
      - '--authrpc.jwtsecret=/run/secrets/jwt.hex'
      - '--state.scheme=path'
      - '--port=30304'
      - '--discovery.port=30304'
    networks:
      traefik:
      internal:
        aliases:
          - 'geth-internal'
      public-facing:
    ports:
      - target: 30304
        published: 30304
        protocol: 'tcp'
        mode: 'host'
      - target: 30304
        published: 30304
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'geth-data'
        target: '/data'

  lodestar:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-testnets'
    # https://hub.docker.com/r/chainsafe/lodestar/tags
    image: 'chainsafe/lodestar:v1.27.1@sha256:4c9e5fc16ee9e29fdffefc91963bc94501a639bc0ca572a31e717e68a2d2c01d'
    command:
      - 'beacon'
      - '--dataDir=/data'
      - '--rest'
      - '--rest.address=0.0.0.0'
      - '--rest.namespace=*'
      - '--execution.urls=http://geth-internal:8551'
      - '--network=holesky'
      - '--port=9001'
      - '--metrics'
      - '--checkpointSyncUrl=https://holesky.beaconstate.info/' # temporary workaround for chainsafe checkpoint sync server being down
      # - '--checkpointSyncUrl=https://beaconstate-holesky.chainsafe.io'
      - '--jwt-secret=/run/secrets/jwt.hex'
    environment:
      NODE_OPTIONS: '--max-old-space-size=8192'
    networks:
      internal:
      public-facing:
    ports:
      - target: 9001
        published: 9001
        protocol: 'tcp'
        mode: 'host'
      - target: 9001
        published: 9001
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'lodestar-data'
        target: '/data'

secrets:
  jwt-secret.hex:
    external: true

networks:
  internal:
  public-facing:
    external: true
  traefik:
    external: true

volumes:
  geth-data:
  lodestar-data:
