services:
  geth:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-geth-worker'
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.my-geth-rpc-router.tls=true'
        - 'traefik.http.routers.my-geth-rpc-router.rule=Host(`geth.dark.florist`) || (Host(`rpc.dark.florist`) && Path(`/winedancemuffinborrow`)) || Host(`ethereum.dark.florist`) || Host(`ethereum.zoltu.io`) || Host(`ethereum.keydonix.com`)'
        - 'traefik.http.routers.my-geth-rpc-router.service=my-geth-rpc-service'
        - 'traefik.http.services.my-geth-rpc-service.loadbalancer.server.port=8545'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # https://hub.docker.com/layers/ethereum/client-go/v1.16.7/images/sha256-9dc2db05933ea9b359b4c07960931ef75f42f8f411018c825eb95d882e82fdc1 amd64
    image: 'ethereum/client-go:v1.16.7@sha256:9dc2db05933ea9b359b4c07960931ef75f42f8f411018c825eb95d882e82fdc1'
    command:
      - '--mainnet'
      - '--datadir=/data'
      - '--http'
      - '--http.addr=0.0.0.0'
      - '--http.port=8545'
      - '--http.vhosts=*'
      - '--http.corsdomain=*'
      - '--http.rpcprefix=/' # serve on all paths
      - '--cache=2048'
      - '--maxpeers=40'
      - '--authrpc.addr=0.0.0.0'
      - '--authrpc.port=8551'
      - '--authrpc.vhosts=*'
      - '--authrpc.jwtsecret=/run/secrets/jwt.hex'
      - '--state.scheme=path'
      - '--history.chain=postmerge'
    networks:
      traefik:
      internal:
        aliases:
          - 'geth-internal'
      public-facing:
    ports:
      - target: 30303
        published: 30303
        protocol: 'tcp'
        mode: 'host'
      - target: 30303
        published: 30303
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'geth-data'
        target: '/data'

  lodestar:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-geth-worker'
    # https://hub.docker.com/r/chainsafe/lodestar/tags
    image: 'chainsafe/lodestar:v1.29.0@sha256:71fab3791140b1282a370da6387b511f19804c03aa1ccfafb09007ac0be95208'
    command:
      - 'beacon'
      - '--dataDir=/data'
      - '--rest'
      - '--rest.address=0.0.0.0'
      - '--rest.namespace=*'
      - '--execution.urls=http://geth-internal:8551'
      - '--network=mainnet'
      - '--port=9000'
      - '--metrics'
      - '--checkpointSyncUrl=https://beaconstate-mainnet.chainsafe.io'
      - '--jwt-secret=/run/secrets/jwt.hex'
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    networks:
      internal:
      public-facing:
    ports:
      - target: 9000
        published: 9000
        protocol: 'tcp'
        mode: 'host'
      - target: 9000
        published: 9000
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'lodestar-data'
        target: '/data'

secrets:
  jwt-secret.hex:
    external: true

networks:
  internal:
  public-facing:
    external: true
  traefik:
    external: true

volumes:
  geth-data:
  lodestar-data:
