services:
  nethermind:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-nethermind'
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.my-nethermind-rpc-router.tls=true'
        - 'traefik.http.routers.my-nethermind-rpc-router.rule=Host(`nethermind.dark.florist`) || (Host(`rpc.dark.florist`) && Path(`/birdchalkrenewtip`)) || (Host(`rpc.dark.florist`) && Path(`/flipcardtrustone`))'
        - 'traefik.http.routers.my-nethermind-rpc-router.service=my-nethermind-rpc-service'
        - 'traefik.http.services.my-nethermind-rpc-service.loadbalancer.server.port=8545'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # https://hub.docker.com/r/nethermindeth/nethermind/tags
    image: 'nethermind/nethermind:1.31.4-chiseled@sha256:2822ce09240bed0c277df588c47826e6d531ad88e109e99797f54db0243f63a5'
    environment:
      NETHERMIND_CONFIG: 'mainnet'
      NETHERMIND_HEALTHCHECKSCONFIG_ENABLED: 'true'
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: 'true'
      NETHERMIND_INITCONFIG_MEMORYHINT: '24000000000'
      NETHERMIND_JSONRPCCONFIG_ENABLED: 'true'
      NETHERMIND_JSONRPCCONFIG_HOST: '0.0.0.0'
      NETHERMIND_JSONRPCCONFIG_PORT: '8545'
      NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES: 'Eth,Subscribe,Trace,Proof,TxPool,TxProof,Net,Web3,Multicall,Parity'
      NETHERMIND_JSONRPCCONFIG_ADDITIONALRPCURLS: 'http://0.0.0.0:8551|http;ws|net;eth;subscribe;engine;web3;client'
      NETHERMIND_JSONRPCCONFIG_JWTSECRETFILE: '/run/secrets/jwt.hex'
      NETHERMIND_SYNCCONFIG_SNAPSYNC: 'true'
      NETHERMIND_SYNCCONFIG_FASTBLOCKS: 'true'
      NETHERMIND_PRUNINGCONFIG_FULLPRUNINGTRIGGER: 'StateDbSize'
    networks:
      traefik:
      internal:
        aliases:
          - 'nethermind-internal'
      public-facing:
    ports:
      - target: 30303
        published: 30303
        protocol: 'tcp'
        mode: 'host'
      - target: 30303
        published: 30303
        protocol: 'udp'
        mode: 'host'
    configs:
      - source: 'nethermind-NLog.config'
        target: '/nethermind/NLog.config'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'nethermind-data'
        target: '/nethermind/nethermind_db'
      - type: 'volume'
        source: 'nethermind-keystore'
        target: '/nethermind/keystore'
      - type: 'volume'
        source: 'nethermind-logs'
        target: '/nethermind/logs'

  lodestar:
    deploy:
      mode: 'global'
      restart_policy:
        condition: 'any'
      placement:
        constraints:
          - 'node.hostname == cherry-lithuania-nethermind'
    # https://hub.docker.com/r/chainsafe/lodestar/tags
    image: 'chainsafe/lodestar:v1.27.1@sha256:4c9e5fc16ee9e29fdffefc91963bc94501a639bc0ca572a31e717e68a2d2c01d'
    command:
      - 'beacon'
      - '--dataDir=/data'
      - '--rest'
      - '--rest.address=0.0.0.0'
      - '--rest.namespace=*'
      - '--execution.urls=http://nethermind-internal:8551'
      - '--network=mainnet'
      - '--port=9000'
      - '--metrics'
      - '--checkpointSyncUrl=https://beaconstate-mainnet.chainsafe.io'
      - '--jwt-secret=/run/secrets/jwt.hex'
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    networks:
      internal:
      public-facing:
    ports:
      - target: 9000
        published: 9000
        protocol: 'tcp'
        mode: 'host'
      - target: 9000
        published: 9000
        protocol: 'udp'
        mode: 'host'
    secrets:
      - source: 'jwt-secret.hex'
        target: '/run/secrets/jwt.hex'
    volumes:
      - type: 'volume'
        source: 'lodestar-data'
        target: '/data'

configs:
  nethermind-NLog.config:
    external: true

secrets:
  jwt-secret.hex:
    external: true

networks:
  internal:
  public-facing:
    external: true
  traefik:
    external: true

volumes:
  nethermind-data:
  nethermind-logs:
  nethermind-keystore:
  lodestar-data:
